# Generated by Django 3.2.20 on 2023-07-20 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, unique=True)),
                ('path', models.TextField(db_index=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FrequencyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Frontend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Polarization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, unique=True)),
                ('file', models.OneToOneField(help_text='The FITS file this Session data was pulled from', on_delete=django.db.models.deletion.CASCADE, to='rfi.file')),
                ('project', models.ForeignKey(help_text='The Project this Session belongs to', on_delete=django.db.models.deletion.CASCADE, to='rfi.project')),
            ],
            options={
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mjd', models.DecimalField(db_index=True, decimal_places=3, max_digits=8)),
                ('datetime', models.DateTimeField(db_index=True, null=True)),
                ('frequency_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfi.frequencytype')),
                ('frontend', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rfi.frontend')),
                ('polarization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfi.polarization')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfi.session')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfi.source')),
            ],
            options={
                'unique_together': {('session', 'mjd')},
            },
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.FloatField()),
                ('intensity', models.FloatField(help_text='Intensity in Jy', null=True)),
                ('scan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rfi.scan')),
            ],
            options={
                'unique_together': {('scan', 'frequency')},
            },
        ),
    ]
